-- Find total customers by countries
SELECT
country,
COUNT(Customer_key) total_cstomers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_cstomers DESC

-- Find total customers by gender
SELECT
gender,
COUNT(Customer_key) total_cstomers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_cstomers DESC

-- Find total products by category
SELECT
category,
COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the eaverage costs in each category?
SELECT
category,
AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category costs in each category?
SELECT 
p.category,
SUM(s.sales_amount) as total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- What is the total revenue generated by each customer?
SELECT 
cu.customer_key,
cu.first_name,
cu.last_name,
SUM(sl.sales_amount) as total_revenue
FROM gold.fact_sales sl
LEFT JOIN gold.dim_customers cu
ON cu.customer_key = sl.customer_key
GROUP BY cu.customer_key,
cu.first_name,
cu.last_name
ORDER BY total_revenue DESC

--What is the distribution of sold items across countries
SELECT
cu.country,
SUM(sl.price) as total_sold_items
FROM gold.fact_sales sl
LEFT JOIN gold.dim_customers cu
ON cu.customer_key = sl.customer_key
GROUP BY country
ORDER BY total_sold_items  DESC





