/*
Magnitude Analysis - Comparing the measure values by categoriess to help us understand
the importance of different categories - [Measure] BY [Dimension]
*/ 

-- Find total customers by countries
	SELECT COUNT(customer_key) AS total_customers, country
	FROM gold.dim_customers
	GROUP BY country
	ORDER BY total_customers DESC

-- Find total customers by gender
	SELECT COUNT(customer_key) AS total_customers, gender
	FROM gold.dim_customers
	GROUP BY gender
	ORDER BY total_customers DESC

-- Find total products by category
	SELECT COUNT(product_key) total_products, category
	FROM gold.dim_products
	GROUP BY category
	ORDER BY total_products DESC

-- What is the average costs in each category?
   SELECT AVG(cost) AS average_cost, category
   FROM gold.dim_products
   GROUP BY category
   ORDER BY average_cost DESC

-- What is the total revenue generated for each category?
   SELECT SUM(sl.sales_amount) AS total_revenue, pd.category
   FROM gold.fact_sales sl
   LEFT JOIN gold.dim_products pd
   ON sl.product_key = pd.product_key
   GROUP BY pd.category
   ORDER BY total_revenue DESC

-- Find total revenue generated by each customer
	SELECT sl.customer_key, 
	      cu.first_name, 
		  cu.last_name,
		  SUM(sl.sales_amount) as total_revenue
	FROM gold.fact_sales sl
	LEFT JOIN gold.dim_customers cu
	ON cu.customer_key = sl.customer_key
	GROUP BY sl.customer_key, cu.first_name, cu.last_name
	ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries
	SELECT 
	cu.country,
	SUM(sl.quantity) AS total_quantities
	FROM gold.fact_sales sl
	LEFT JOIN gold.dim_customers cu
	ON cu.customer_key = sl.customer_key
	GROUP BY cu.country
	ORDER BY total_quantities DESC